pipeline{
   agent any
   stages{
          stage('Build') {
              
            steps {
                sh "cd django"
                sh "cat docker-compose-aws.yml"
            }
        }   
   }
}
